---
- name: update homepi
  hosts: all
  become: true
  tasks:
    - name: shutdown services
      systemd:
        state: stopped
        name: "{{ item }}"
      loop:
        - homegear
        - mosquitto
    - name: Update Cache and upgrade
      apt:
          update_cache: yes
          upgrade: dist
      become: yes
    - name: restart home services
      systemd:
        state: started
        name: "{{ item }}"
      loop:
        - homegear
        - mosquitto
