---
- name: check for k8sfile and create if not there
  file:
    path: /etc/sysctl.d/k8s.conf
    state: touch

- name: check for lines in k8sfile
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    state: present
    regexp: "^{{ item }}$"
    line: "{{ item }}"
  loop:
    - "net.bridge.bridge-nf-call-ip6tables = 1"
    - "net.bridge.bridge-nf-call-iptables = 1"