---
- name: Check if swap enabled
  shell: swapon -s | wc -l
  register: swap_enabled

- name: Disable swap
  shell: "{{ item }}"
  with_items: 
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - systemctl disable dphys-swapfile.service
  when: swap_enabled.stdout != "1"