---
- name: enable cgroups for Raspberry Pi
  become: true
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  loop:
    - "cgroup_enable=cpuset"
    - "cgroup_enable=memory"
    - "cgroup_memory=1"
    - "swapaccount=1"